version: '3.5'

services:
  machine1:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-030.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
        - vdi-linux-030.ccs.neu.edu
    volumes:
    - "./:/code"


  machine2:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-031.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
        - vdi-linux-031.ccs.neu.edu
    volumes:
    - "./:/code"


  machine3:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-032.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
        - vdi-linux-032.ccs.neu.edu
    volumes:
    - "./:/code"


  machine4:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-033.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
        - vdi-linux-033.ccs.neu.edu
    volumes:
    - "./:/code"

  machine5:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-034.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
        - vdi-linux-034.ccs.neu.edu
    volumes:
    - "./:/code"

  machine6:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-035.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
          - vdi-linux-035.ccs.neu.edu
    volumes:
      - "./:/code"

  machine7:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-036.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
          - vdi-linux-036.ccs.neu.edu
    volumes:
      - "./:/code"

  machine8:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-037.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
          - vdi-linux-037.ccs.neu.edu
    volumes:
      - "./:/code"

  machine9:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-038.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
          - vdi-linux-038.ccs.neu.edu
    volumes:
      - "./:/code"

  machine10:
    image: python:3
    command: python -u dynamo.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-039.ccs.neu.edu
    working_dir: /code
    networks:
      neunet:
        aliases:
          - vdi-linux-039.ccs.neu.edu
    volumes:
      - "./:/code"

  client1:
    image: python:3
    command: python -u client.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-040.ccs.neu.edu
    working_dir: /code
    stdin_open: true
    tty: true
    networks:
      neunet:
        aliases:
        - vdi-linux-040.ccs.neu.edu
    volumes:
    - "./:/code"

  testcases:
    image: python:3
    command: python -u test_cases.py --leader vdi-linux-030.ccs.neu.edu --port 13337
    hostname: vdi-linux-041.ccs.neu.edu
    working_dir: /code
    stdin_open: true
    tty: true
    networks:
      neunet:
        aliases:
          - vdi-linux-041.ccs.neu.edu
    volumes:
      - "./:/code"

networks:
  neunet:
    driver: bridge